# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['limiter.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('telegram_bot', 'telegram_bot'),
        ('utils', 'utils'),
    ],
    hiddenimports=[
        # Core project modules
        'telegram_bot',
        'telegram_bot.main',
        'telegram_bot.send_message',
        'telegram_bot.utils',
        'utils',
        'utils.check_usage',
        'utils.get_logs',
        'utils.handel_dis_users',
        'utils.connection_analyzer',
        'utils.isp_detector',
        'utils.logs',
        'utils.panel_api',
        'utils.parse_logs',
        'utils.read_config',
        'utils.types',
        'utils.warning_system',
        'run_telegram',
        # Third-party packages
        'telegram',
        'telegram.ext',
        'httpx',
        'httpx._client',
        'httpx._config',
        'httpx._exceptions',
        'httpx._models',
        'httpx._types',
        'httpx._utils',
        'httpx._auth',
        'httpx._content',
        'httpx._decoders',
        'httpx._transports',
        'httpcore',
        'h11',
        'h2',
        'certifi',
        'charset_normalizer',
        'idna',
        'sniffio',
        'anyio',
        'typing_extensions',
    ],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='limiter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
